In [11]:
import h5py
import numpy as np

In [12]:
VIST_example_fmap = h5py.File('VIST_example_fmap.h5', 'r')
len(VIST_example_fmap.keys())

110

In [13]:
for k in VIST_example_fmap.keys():
    pass

In [14]:
VIST_example_fmap['10'].shape

(1, 512, 37, 37)

In [15]:
# VIST_example_fmap['10'][0, :, 0, 0]

In [16]:
VIST_val_fmap = h5py.File('VIST_val_fmap.h5', 'r')
len(VIST_val_fmap.keys())

21017

In [17]:
max([int(k) for k in VIST_val_fmap.keys()])

21022

In [18]:
VIST_test_fmap = h5py.File('VIST_test_fmap.h5', 'r')
len(VIST_test_fmap.keys())

20988

In [19]:
for k in VIST_test_fmap.keys():
    pass

In [20]:
VIST_example_obj_fmap = h5py.File('VIST_example_obj_fmap.h5', 'r')
len(VIST_example_obj_fmap.keys())

110

In [21]:
VIST_example_obj_fmap.keys()

<KeysViewHDF5 ['0', '1', '10', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '4', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '5', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '6', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '7', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '8', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '9', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99']>

In [22]:
VIST_example_obj_fmap['10'].shape

(64, 4096)

In [23]:
for k, v in VIST_example_obj_fmap.items():
    print (k,v)
    print (np.average(v, axis=0))

0 <HDF5 dataset "0": shape (64, 4096), type "<f4">
[0.02814754 0.00503074 0.03090706 ... 0.01165713 0.00233698 0.02271476]
1 <HDF5 dataset "1": shape (64, 4096), type "<f4">
[0.01349307 0.04231006 0.04058608 ... 0.05359643 0.03571505 0.01974095]
10 <HDF5 dataset "10": shape (64, 4096), type "<f4">
[0.00125645 0.01231863 0.01206672 ... 0.05040733 0.15967956 0.02498051]
100 <HDF5 dataset "100": shape (64, 4096), type "<f4">
[5.2892799e-03 7.0752405e-02 6.9695234e-02 ... 1.4825205e-02 5.1509898e-02
 2.4888235e-05]
101 <HDF5 dataset "101": shape (64, 4096), type "<f4">
[0.01243369 0.03137998 0.03577782 ... 0.00653092 0.0774489  0.00449815]
102 <HDF5 dataset "102": shape (64, 4096), type "<f4">
[0.02338076 0.02080241 0.02369728 ... 0.02904405 0.08725914 0.07107975]
103 <HDF5 dataset "103": shape (64, 4096), type "<f4">
[0.00181055 0.0376429  0.02302538 ... 0.01879059 0.17794213 0.03510687]
104 <HDF5 dataset "104": shape (64, 4096), type "<f4">
[0.00980411 0.04607674 0.05387633 ... 0.0296590

[0.01155159 0.0273391  0.05217311 ... 0.0092052  0.07958206 0.        ]
67 <HDF5 dataset "67": shape (64, 4096), type "<f4">
[0.00209584 0.03114202 0.03732676 ... 0.00646941 0.09751507 0.05028123]
68 <HDF5 dataset "68": shape (64, 4096), type "<f4">
[0.00352141 0.00455324 0.01280629 ... 0.05260136 0.04095691 0.01411786]
69 <HDF5 dataset "69": shape (60, 4096), type "<f4">
[0.02216128 0.00129647 0.00955258 ... 0.00997459 0.05015583 0.08149929]
7 <HDF5 dataset "7": shape (64, 4096), type "<f4">
[0.00065476 0.02210393 0.03146643 ... 0.01933616 0.05741847 0.00443231]
70 <HDF5 dataset "70": shape (64, 4096), type "<f4">
[0.00304956 0.0388763  0.01408199 ... 0.03009582 0.08892425 0.02245906]
71 <HDF5 dataset "71": shape (64, 4096), type "<f4">
[0.01167964 0.07501193 0.05936682 ... 0.04207942 0.10900062 0.03634388]
72 <HDF5 dataset "72": shape (64, 4096), type "<f4">
[0.01331689 0.02467094 0.04291793 ... 0.00207457 0.0928617  0.04131328]
73 <HDF5 dataset "73": shape (64, 4096), type "<f4">
[3

In [24]:
VIST_example_fmap.close()
VIST_example_obj_fmap.close()

In [25]:
VIST_train_obj_fmap = h5py.File('VIST_train_obj_fmap.h5', 'r')
VIST_valid_obj_fmap = h5py.File('VIST_val_obj_fmap.h5', 'r')
VIST_test_obj_fmap = h5py.File('VIST_test_obj_fmap.h5', 'r')

In [26]:
import json
with open('../data/vist_train/VIST_image_data.json', 'r') as f:
    train_idx2flickrID = json.load(f)
with open('../data/vist_val/VIST_image_data.json', 'r') as f:
    val_idx2flickrID = json.load(f)
with open('../data/vist_test/VIST_image_data.json', 'r') as f:
    test_idx2flickrID = json.load(f)

In [28]:
paired_list = [
    (VIST_train_obj_fmap, train_idx2flickrID), 
    (VIST_valid_obj_fmap, val_idx2flickrID), 
    (VIST_test_obj_fmap, test_idx2flickrID)
]

In [31]:
VIST_all_global = {}
for obj_map, idx2flickrID in paired_list:
    for k, v in obj_map.items():
        flickrID = idx2flickrID[int(k)]['flickr_id']
#         print (k, flickrID)
        global_feat = np.average(v, axis=0)
        VIST_all_global[flickrID] = global_feat


In [32]:
len(VIST_all_global)



209038

In [16]:
# for k, v in VIST_valid_obj_fmap.items():
#     global_feat = np.average(v, axis=0)
#     VIST_all_global[k] = global_feat
    

In [33]:
len(VIST_all_global)

209038

In [34]:
# for k, v in VIST_test_obj_fmap.items():
#     global_feat = np.average(v, axis=0)
#     VIST_all_global[k] = global_feat
    

In [35]:
len(VIST_all_global)

209038

In [36]:
# for k, v in VIST_train_obj_fmap.items():
#     global_feat = np.average(v, axis=0)
#     VIST_all_global[k] = global_feat
    

In [37]:
len(VIST_all_global)

209038

In [38]:
list(VIST_all_global.keys())[200]

'1176709'

In [40]:
import pickle
with open('VIST_all_avg.pkl', 'wb') as f: 
    pickle.dump(VIST_all_global, f, protocol=2)